version: "3.9"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - mongo
    restart: always

networks:
  mongo:
    driver: bridge

volumes:
  mongodb:
