version: "3.5"

services:
  redis:
    image: bitnami/redis:7.0
    container_name: redis
    environment:
      - REDIS_PASSWORD=password
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    networks:
      - redis
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    depends_on:
      - redis
    ports:
      - 8001:8001
    networks:
      - redis
    restart: always

networks:
  redis:
    driver: bridge

volumes:
  redis_data:
