version: "3.0"

services:
  nvidia-pytorch:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/src
      - huggingface_cache:/root/.cache/huggingface
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  huggingface_cache:
    driver: local
